### ISSUE TITLE
Allow scripts to reside in subfolders

### ISSUE THREAD

**Issue by dazKind** [HaxeGodot/editor-plugin#2]
When creating new Haxe-Scripts on a Node in Godot you can specify to create it inside a subfolder like `<projectroot>/scripts/extensions/Trail.hx`. 

In this case the editor will fail with the following output and not attach the script correctly: 
![image](https://user-images.githubusercontent.com/73549123/117368930-8568e800-aec4-11eb-9f3e-ba64939e26d1.png)

If the script in question is created directly inside the scripts folder `<projectroot>/scripts/Trail.hx` everything works as expected. 

For code organisation purposes it would rock to allow for subfolders cause I can already see this growing into a quite a busy scripts folder as one project grows. What do you think?

**Comment by ibilon** [comment]
That's a bug, I think the output subfolder isn't created so it fails,
definitely something that should work I agree.

**Comment by ibilon** [comment]
Should work now.

**Comment by dazKind** [comment]
![image](https://user-images.githubusercontent.com/5015415/117510497-76e60380-af8c-11eb-9548-aae99091942f.png)
Creation works, but I cant get it to compile.

![image](https://user-images.githubusercontent.com/5015415/117510410-528a2700-af8c-11eb-8b55-727a91fc9c45.png)

**Comment by dazKind** [comment]
See https://github.com/HaxeGodot/godot/pull/4 for a fix
