### ISSUE TITLE
Installation / enable plugin error: Unable to load addon script from path: 'res://addons/haxe/editor-plugin-main/scripts/haxe.gd' There seems to be an error in the code, please check the syntax.

### ISSUE THREAD

**Issue by jcward** [HaxeGodot/editor-plugin#4]
Following the installation instructions, when trying to enable the plugin, I get the following error:

```
Unable to load addon script from path: 'res://addons/haxe/editor-plugin-main/scripts/haxe.gd' There seems to be an error in the code, please check the syntax.
```

**Comment by jcward** [comment]
It's because I downloaded this editor repo using [the download link](https://github.com/HaxeGodot/editor-plugin/archive/refs/heads/main.zip) in the README, and unzipped it in `addons/haxe`, but github creates an extra directory level. I ended up moving the files out of the sub-directory like this:

```
cd <project_dir>
mkdir -p addons/haxe
cd addons/haxe
unzip ~/Downloads/editor-plugin-main.zip
mv editor-plugin-main/* .
rmdir editor-plugin-main
```

Then the plugin can be successfully enabled:

![image](https://user-images.githubusercontent.com/2192439/130533506-b2670d57-7710-46f8-a0e5-bd3b47b6590a.png)

**Comment by ibilon** [comment]
Good catch, I'll update the readme.
