### ISSUE TITLE
README - might note Haxe 4.2+

### ISSUE THREAD

**Issue by jcward** [HaxeGodot/editor-plugin#5]
Setup.hx uses module-level functions, which [I believe require](https://haxe.org/blog/module-level-fields/) Haxe 4.2+

The README.md might mention this.

Are there other Haxe version requirements?

**Comment by ibilon** [comment]
I don't think there are more requirements.

I did a module function because I became used to them, but there's no real reason here, I'll wrap a main class around to lower the required haxe version.
