### ISSUE TITLE
Module Setup does not define Setup

### ISSUE THREAD

**Issue by rayanmargham** [HaxeGodot/editor-plugin#6]
![image](https://user-images.githubusercontent.com/69608259/131227539-e0f3715a-7f93-466a-9437-d1dc2f3e1c62.png)
When attempting to "Setup" the plugin it spits out this error.

# Steps To Reproduce
download the plugin and put it in your project folder
create a c# solution.
Project -> Tools -> Haxe -> Setup
see this error

**Comment by ibilon** [comment]
Got the name wrong on my last fix, should work now.
