### ISSUE TITLE
Cannot access the ArrayIterator constructor.

### ISSUE THREAD

**Issue by Terria-K** [HaxeGodot/editor-plugin#7]
It looks like the constructor of ArrayIterator is private, so the Array.hx cannot access it. I got this error whenever I build the haxe project.
![haxe](https://user-images.githubusercontent.com/86240437/140318036-d3df7501-ad11-4495-8609-8b0cb264bd19.png)

**Comment by ibilon** [comment]
It should be fixed by https://github.com/HaxeGodot/godot/commit/e76f9edfc701ea69513086290cf41c041af44c36.

**Comment by ibilon** [comment]
Fixed now on the haxelib version 3.4.1.
